### ISSUE TITLE
NPE when rerunning test from JUnit View whose file has been moved

### ISSUE THREAD

**Issue by joergreichertn4** [eclipse/Xpect#141]
scenario: rerunning XPECT test whose file has been moved in the meanwhile

java.lang.NullPointerException
    at org.xpect.runner.XpectTestFiles$XpectTestFileCollector.deresolveToProject(XpectTestFiles.java:107)
    at org.xpect.runner.DescriptionFactory.createFileDescriptionForError(DescriptionFactory.java:34)
    at org.xpect.runner.XpectFileRunner.createDescription(XpectFileRunner.java:121)
    at org.xpect.runner.XpectFileRunner.getDescription(XpectFileRunner.java:181)
    at org.xpect.runner.XpectRunner.describeChild(XpectRunner.java:121)
    at org.xpect.runner.XpectRunner.describeChild(XpectRunner.java:1)
    at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:298)
    at org.eclipse.jdt.junit4.runtime.patch.JUnit4TestMethodReference.<init>(JUnit4TestMethodReference.java:29)
    at org.eclipse.jdt.junit4.runtime.patch.JUnit4TestLoader.createTest(JUnit4TestLoader.java:50)
    at org.eclipse.jdt.junit4.runtime.patch.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:34)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by cdietrich** [comment]
the same problem happens if there are files listed in `@XpectTestFiles` that dont exist. i would expect a proper error message
