### ISSUE TITLE
NPE on simple test

### ISSUE THREAD

**Issue by magick93** [eclipse/Xpect#236]
Hello

I am just getting started with Xpect so I have probably not setup correctly. However I cannot find what I have done wrong.

When I try to run the below test, it fails due to a NPE error:

```
java.lang.NullPointerException
	at org.xpect.xtext.lib.setup.XtextStandaloneSetup.<init>(XtextStandaloneSetup.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.xpect.state.StateContainer.createFactory(StateContainer.java:154)
	at org.xpect.state.StateContainer.getFactory(StateContainer.java:271)
	at org.xpect.state.StateContainer.createInstance(StateContainer.java:174)
	at org.xpect.state.StateContainer.createInstance(StateContainer.java:198)
	at org.xpect.state.StateContainer.get(StateContainer.java:248)
	at org.xpect.state.StateContainer.get(StateContainer.java:210)
	at org.xpect.state.StateContainer.createFactory(StateContainer.java:150)
	at org.xpect.state.StateContainer.getFactory(StateContainer.java:271)
	at org.xpect.state.StateContainer.createInstance(StateContainer.java:174)
	at org.xpect.state.StateContainer.createInstance(StateContainer.java:198)
	at org.xpect.state.StateContainer.get(StateContainer.java:248)
	at org.xpect.state.StateContainer.get(StateContainer.java:210)
	at org.xpect.runner.XpectFileRunner.run(XpectFileRunner.java:135)
	at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:208)
	at org.xpect.runner.XpectRunner.runChild(XpectRunner.java:1)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.xpect.runner.XpectRunner.run(XpectRunner.java:194)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

```

Xpect test
-------------
```
/* XPECT_SETUP group.yestech.sculptor.tests.MyXtextTests END_SETUP */

Application Library {
  // XPECT linkedName at String --> java.lang.String
  basePackage = org.library
    
  Module media {
  	
  	Entity Library {
      scaffold
      String name key
      - Set<@PhysicalMedia> media <-> library
    
      Repository LibraryRepository {
        findByQuery;
        @Library findLibraryByName(String name) throws LibraryNotFoundException;
      }
    }
    
    Service LibraryService {
      findLibraryByName => LibraryRepository.findLibraryByName;
      findMediaByName => MediaRepository.findMediaByName;
      findMediaByCharacter => MediaRepository.findMediaByCharacter;
      findPersonByName => PersonService.findPersonByName;
    }
    
    
    
    Entity PhysicalMedia {
      scaffold
      String status length="3"
      String location
      - @Library library nullable <-> media
      - Set<@Media> media <-> physicalMedia
    }
    
    Service MediaService {
      findAll => MediaRepository.findAll;
    }
    
    abstract Entity Media {
      gap
      String title !changeable
      - Set<@PhysicalMedia> physicalMedia inverse <-> media
      - Set<@Engagement> engagements cascade="all-delete-orphan" <-> media
      - Set<@MediaCharacter> mediaCharacters <-> existsInMedia
    
      Repository MediaRepository {
        > @MediaCharacterRepository
        int getNumberOfMovies(Long libraryId) => AccessObject;
        List<@Media> findMediaByCharacter(Long libraryId, String characterName);
        findById;
        save;
        findAll;
        findByQuery;
        protected findByKeys(Set<String> keys, String keyPropertyName, Class persistentClass);
        List<@Media> findMediaByName(Long libraryId, String name);
        Map<String, @Movie> findMovieByUrlIMDB(Set<String> keys);
      }
    }
    
    Entity Book extends @Media {
      !auditable
      String isbn key length="20"
    }
    
    Entity Movie extends @Media {
      !auditable
      String urlIMDB key
      Integer playLength
      - @Genre category nullable
    }
    
    enum Genre {
      ACTION,
      COMEDY,
      DRAMA,
      SCI_FI
    }
    
    ValueObject Engagement {
      String role
      - @Person person
      - @Media media <-> engagements
    }
    
    Service MediaCharacterService {
      findAll => MediaCharacterRepository.findAll;
    }
    
    ValueObject MediaCharacter {
      String name !changeable
      - Set<@Person> playedBy
      - Set<@Media> existsInMedia <-> mediaCharacters
    
      Repository MediaCharacterRepository {
        findByQuery;
        findAll;
      }
    }
  }
    
  Module person {
    Service PersonService {
      findPersonByName => PersonRepository.findPersonByName;
    }
    
    Entity Person {
      gap
      scaffold
      Date birthDate past
      - @Gender sex !changeable
      - @Ssn ssn key
      - @PersonName name
    
      Repository PersonRepository {
        List<@Person> findPersonByName(String name) => AccessObject;
        save;
        save(Collection<@Person> entities);
        findByQuery;
        findByExample;
        findByKeys;
      }
    }
    
    BasicType Ssn {
      String number key length="20"
      - @Country country key
    }
    
    BasicType PersonName {
      String first
      String last
    }
      
  }
}
```

**Comment by cdietrich** [comment]
how does MyXtextTests look like? did you debug where the npe happens?

**Comment by cdietrich** [comment]
btw do you use the old xpect codebase and not the new one from eclipse?

**Comment by magick93** [comment]
I havent figured out how to debug xpect tests yet.


Im using Xpect from the update site.
Version
-----------
 Xpect SDK Feature	0.2.0.201706301756

MyXtextTests
------------------

```
package group.yestech.sculptor.tests;

import org.junit.runner.RunWith;
import org.xpect.runner.XpectRunner;
import org.xpect.xtext.lib.tests.XtextTests;

@RunWith(XpectRunner.class)
@SuppressWarnings("all")
public class MyXtextTests extends XtextTests {
}

```

**Comment by cdietrich** [comment]
debugging should work the same as for normal unit tests.
i miss somewhere a hint which files to use. how is your testfile named?

**Comment by cdietrich** [comment]
@mmews-n4 is there any releases planned on eclipse side?

**Comment by magick93** [comment]
- mytest.domian.xt
- MyXtextTests.xtend

**Comment by cdietrich** [comment]
does that test project have a dependency to mydsl.ui?

**Comment by cdietrich** [comment]
alternatively: did you use the extension point to register the language to xpect:
```
<?xml version="1.0" encoding="UTF-8"?>
<?eclipse version="3.4"?>
<plugin>
   <extension
         point="org.xpect.fileExtensions">
      <fileExtension
            fileExtension="mydsl"
            xtextLanguageName="org.xtext.example.mydsl.MyDsl"
            xtextRuntimeModule="org.xtext.example.mydsl.MyDslRuntimeModule">
      </fileExtension>
   </extension>

</plugin>
```

**Comment by mmews-n4** [comment]
As far as I know, we don't plan any new release soon.
@cdietrich Thanks for your help!
