### ISSUE TITLE
Build does not work

### ISSUE THREAD

**Issue by cdietrich** [eclipse/Xpect#295]
12:25:00  Caused by: java.lang.ClassNotFoundException: io.github.toolfactory.jvm.Driver
12:25:00  	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
12:25:00  	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
12:25:00  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
12:25:00  	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
12:25:00  	... 39 more

https://github.com/classgraph/classgraph/issues/568

**Comment by cdietrich** [comment]
complete message

```
0    [main] ERROR egistry.StandaloneExtensionRegistry  - io/github/toolfactory/jvm/Driver
java.lang.NoClassDefFoundError: io/github/toolfactory/jvm/Driver
	at io.github.classgraph.ModulePathInfo.<init>(ModulePathInfo.java:136)
	at nonapi.io.github.classgraph.scanspec.ScanSpec.<init>(ScanSpec.java:231)
	at io.github.classgraph.ClassGraph.<init>(ClassGraph.java:67)
	at org.eclipse.xpect.util.ClasspathUtil.findResources(ClasspathUtil.java:55)
	at org.eclipse.xpect.registry.StandaloneExtensionRegistry.collectExtensions(StandaloneExtensionRegistry.java:167)
	at org.eclipse.xpect.registry.StandaloneExtensionRegistry.<init>(StandaloneExtensionRegistry.java:156)
	at org.eclipse.xpect.registry.IExtensionInfo$Registry.<clinit>(IExtensionInfo.java:25)
	at org.eclipse.xpect.registry.EPackageInfoRegistry.collectEPackageInfos(EPackageInfoRegistry.java:71)
	at org.eclipse.xpect.registry.EPackageInfoRegistry.<init>(EPackageInfoRegistry.java:67)
	at org.eclipse.xpect.registry.IEPackageInfo$Registry.<clinit>(IEPackageInfo.java:22)
	at org.eclipse.xpect.registry.StandaloneLanguageRegistry.init(StandaloneLanguageRegistry.java:97)
	at org.eclipse.xpect.registry.StandaloneLanguageRegistry.<init>(StandaloneLanguageRegistry.java:70)
	at org.eclipse.xpect.registry.ILanguageInfo$Registry.<clinit>(ILanguageInfo.java:29)
	at org.eclipse.xpect.util.XpectJavaModelManager.getTypeReferences(XpectJavaModelManager.java:93)
	at org.eclipse.xpect.util.XpectJavaModelManager.createJavaModel(XpectJavaModelManager.java:40)
	at org.eclipse.xpect.runner.XpectRunner.<init>(XpectRunner.java:74)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.ClassNotFoundException: io.github.toolfactory.jvm.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 33 more

```

guess we need a new classgraph for this

**Comment by cdietrich** [comment]
is fixed upstream
